# Generated by Django 3.1.1 on 2020-11-06 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSplit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_split', models.DecimalField(decimal_places=6, max_digits=8)),
                ('time_donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='donations.timedonation')),
            ],
        ),
        migrations.CreateModel(
            name='MoneySplit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money_split', models.DecimalField(decimal_places=6, max_digits=8)),
                ('money_donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='donations.moneydonation')),
            ],
        ),
    ]
