# Generated by Django 3.1.1 on 2020-11-06 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_moneysplit_timesplit'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneysplit',
            name='charity',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='timesplit',
            name='task',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='moneysplit',
            name='money_donation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donations.moneydonation'),
        ),
        migrations.AlterField(
            model_name='moneysplit',
            name='money_split',
            field=models.DecimalField(decimal_places=4, max_digits=5),
        ),
        migrations.AlterField(
            model_name='timesplit',
            name='time_donation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donations.timedonation'),
        ),
        migrations.AlterField(
            model_name='timesplit',
            name='time_split',
            field=models.DecimalField(decimal_places=4, max_digits=5),
        ),
    ]
