# Generated by Django 3.1.1 on 2020-11-13 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_auto_20201113_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('desc', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('desc', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='moneydonation',
            name='charity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donations.charity'),
        ),
        migrations.AlterField(
            model_name='timedonation',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donations.task'),
        ),
    ]
