# Generated by Django 3.1.1 on 2020-11-18 02:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donations', '0008_auto_20201117_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='id',
        ),
        migrations.AlterField(
            model_name='level',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
