# Generated by Django 3.1.1 on 2020-11-23 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0009_auto_20201117_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='fulfilled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='goal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='timedonation',
            name='time_total',
            field=models.IntegerField(default=0),
        ),
    ]
